#! /bin/bash

#SBATCH -p q_student
#SBATCH -N 1                 
#SBATCH -c 32   # use all 32 cores 
#SBATCH --cpu-freq=High
#SBATCH --time=5:00

NLIST=(1000000 10000000 100000000)
MLIST=(2000000 20000000 200000000)
PLIST=(2 4 8 11 16 32)
NREP=10

# CASE="merge1"
CASE="merge2"
#CASE="merge3"

#### my stuff ####
NLIST=(10)
MLIST=(20)
# PLIST=(2)
NOW=$(date +"%D[%T]")
NOW=${NOW//":"/"_"}
NOW=${NOW//"/"/"-"}
SOURCE_ROOT="$HOME/UE1/parmerge-student-1.0.0-Source"
OUT_FOLDER="${SOURCE_ROOT}/job_outputs/${CASE}/run_${NOW}/"
$(mkdir ${OUT_FOLDER})
#### end my stuff #### 

BINARY="${SOURCE_ROOT}/bin/${CASE}_tester"

NL=${#NLIST[@]}

for (( i=0; i<$NL; i++ ));
do
  n=${NLIST[$i]}
  m=${MLIST[$i]}
  for p in "${PLIST[@]}"
  do
    srun ${BINARY} -n $n -m $m -p $p -r $NREP > "${OUT_FOLDER}output_${CASE}_${n}_${m}_${p}.out"
  done
done

# cd ~/UE1/parmerge-student-1.0.0-Source/jobs_files
# sbatch run_parmerge_tests.job